# EmailMKT.Domain.Entity.Customer.dcm.yml
EmailMKT\Domain\Entity\Campaign:
  # Tipo: sempre entidade
  type: entity
  # Declarando repositório personalizado
  repositoryClass: EmailMKT\Infrastructure\Persistence\Doctrine\Repository\CampaignRepository
  # Nome da tabela do BD
  table: campaigns
  # Quando tiver um ID Primario
  id:
    # Nome do campo
    id:
      # tipo do campo
      type: integer
      # Auto incremento
      generator:
        strategy: AUTO

  # Demais campos
  fields:
    # Nome do campo
    name:
      type: string
      length: 150
    # Nome do campo
    template:
      type: text

  #Relacionamento Muitos para Muitos
  manyToMany:
      tags:
        targetEntity: EmailMKT\Domain\Entity\Tag
        mappedBy: campaigns