# EmailMKT.Domain.Entity.Customer.dcm.yml
EmailMKT\Domain\Entity\Tag:
  # Tipo: sempre entidade
  type: entity
  # Nome da tabela do BD
  table: tags
  # Quando tiver um ID Primario
  id:
    # Nome do campo
    id:
      # tipo do campo
      type: integer
      # Auto incremento
      generator:
        strategy: AUTO

  # Demais campos
  fields:
    # Nome do campo
    name:
      type: string
      length: 150

  #Relacionamento Muitos para Muitos
  manyToMany:
    customers:
      targetEntity: EmailMKT\Domain\Entity\Customer
      inversedBy: tags